/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twitter_university_android_ndk_FastAdder */

#ifndef _Included_com_twitter_university_android_ndk_FastAdder
#define _Included_com_twitter_university_android_ndk_FastAdder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twitter_university_android_ndk_FastAdder
 * Method:    addNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_twitter_university_android_ndk_FastAdder_addNative
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
